name: Validate user groups data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_user_groups_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Hello!

